### ISSUE TITLE
Server Software collection / report

### ISSUE THREAD

**Issue by zjassiem** [ska-sa/katsdpnetboxutilities#22]
Software list / report of the software that is installed per server generated in PDF form.

**Comment by martinslabber** [comment]
For Apt add 
`dpkg-query -W | awk 'BEGIN {print "["} {printf "{\"name\": \""$1"\", \"version\": \""$2"\"},"} END {print "]"}' | sed -e " s/,]$/]/g" | jq`
to the collector and represent that as a sorted table in the PDF. Might have to be multiple tables since there was a problem spanning long tables over many pages.

**Comment by martinslabber** [comment]
For Python add
`pip3 list --format=json | jq .`
to the collector and represent that as a sorted table in the PDF.

**Comment by martinslabber** [comment]
The collector is not part of this repo. it is just a few tasks in our Ansible roles.

**Comment by zjassiem** [comment]
FYI
For future reference
@KgomotsoMonnakgotla
